In [15]:
#16min
import numpy as np

def rebuild(U,sigma,V):
    matrix=np.dot(U,sigma)
    matrix=np.dot(matrix,np.transpose(V))
    return matrix

def sorteigen(eigenvalues,eigenvectors):
    index=np.argsort(-1*eigenvalues)
    #重排
    eigenvalues=eigenvalues[index]
    eigenvectors=eigenvectors[:,index]
    return eigenvalues,eigenvectors

def SVD(A,numofleft=None):
    ATA=np.dot(np.transpose(A),A)
    lamdaV,XV=np.linalg.eig(ATA)
    lamdaV,XV=sorteigen(lamdaV,XV)
    sigma=lamdaV
    #确保无负值
    sigma=list(map (lambda x:np.sqrt(x) if x>0 else 0,sigma))
    sigma=np.array(sigma)
    sigmaM=np.diag(sigma)
    
    if numofleft==None:
        rank=len(list(filter(lambda x:x>0,sigma)))
    else:
        rank=numofleft
    #只保留大于0的特征值，为了求V
    sigmaM=sigmaM[0:rank,:]
    
    #下面可以开始计算U（m*r）
    XU=np.zeros((A.shape[0],rank))#初始化
    for i in range(rank):
        XU[:,i]=np.transpose(np.dot(A,XV[:,i]/sigma[i]))
        #ui=1/sigmaj * (A vj)
    
    XV=XV[:,0:numofleft]
    sigmaM=sigmaM[0:numofleft,0:numofleft]
    return XU,sigmaM,XV
        
    
    
    
    

In [17]:
A=np.array([[1,0,0,0],[0,0,0,4],[0,3,0,0],[0,0,0,0],[2,0,0,0]])

In [18]:
A

array([[1, 0, 0, 0],
       [0, 0, 0, 4],
       [0, 3, 0, 0],
       [0, 0, 0, 0],
       [2, 0, 0, 0]])

In [19]:
U,S,V=SVD(A,None)

In [20]:
U


array([[0.        , 0.        , 0.4472136 ],
       [1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.89442719]])

In [21]:
S

array([[4.        , 0.        , 0.        , 0.        ],
       [0.        , 3.        , 0.        , 0.        ],
       [0.        , 0.        , 2.23606798, 0.        ]])

In [22]:
V

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])

In [23]:
rebuild(U,S,V)

array([[1., 0., 0., 0.],
       [0., 0., 0., 4.],
       [0., 3., 0., 0.],
       [0., 0., 0., 0.],
       [2., 0., 0., 0.]])